apiVersion: apps/v1
kind: Deployment
metadata:
  name: myburger-payment
spec:
  selector:
    matchLabels:
      app: myburger-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: myburger-payment
    spec:
      containers:
        - name: myburger-payment
          image: fiapmyburguer/myburger-payment-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "800Mi"
              cpu: "800m"
            requests:
              memory: "512Mi"
              cpu: "600m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: myburger-config
            - secretRef:
                name: myburger-secrets
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health/liveness
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/v1/actuator/health/readiness
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5