apiVersion: v1
kind: ConfigMap
metadata:
  name: myburger-config-order
  labels:
    app: myburger-config-order
data:
  JAVA_OPTS: >-
    -server
    -XX:+UseContainerSupport
    -XX:+UseParallelGC
    -XX:MaxRAMPercentage=70.0
    -XX:ActiveProcessorCount=1600
    -XX:+CrashOnOutOfMemoryError
    -Xlog:gc
  MONGODB_URI: "postgresql://myburger-db-server-do-user-17490961-0.l.db.ondigitalocean.com:25060/my_burger"
  MANAGEMENT_SERVICE_URL: ""
  PAYMENT_SERVICE_URL: ""
