apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myburger-hpa-order
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myburger
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
