apiVersion: v1
kind: ConfigMap
metadata:
  name: myburger-config
  labels:
    app: myburger-config
data:
  JAVA_OPTS: >-
    -server
    -XX:+UseContainerSupport
    -XX:+UseParallelGC
    -XX:MaxRAMPercentage=70.0
    -XX:ActiveProcessorCount=1600
    -XX:+CrashOnOutOfMemoryError
    -Xlog:gc
  MONGODB_URI: "#MONGODB_URI#"
  MANAGEMENT_SERVICE_URL: ""
  PAYMENT_SERVICE_URL: ""
  DATABASE_URL: "postgresql://#PG_DB_HOST#:#PG_DB_PORT#/my_burger"
  LOG_LEVEL: "DEBUG"
  MP_NOTIFICATION_URL: https://concise-humble-mosquito.ngrok-free.app/api/v1/webhook?source_news=ipn
  MP_PAYMENT_URL: https://api.mercadopago.com/v1/payments
  MP_MERCHANT_URL: https://api.mercadolibre.com/merchant_orders
  MP_REQUEST_URL: https://api.mercadopago.com/instore/orders/qr/seller/collectors/1687509/pos/SUC001POS001/qrs
